[TOC]



## 为什么需要异常

> 
> 函数的返回值可以忽略,但异常不可忽略。如果程序出现异常,但是没有被捕获,
> 程序就会终止,这多少会促使程序员开发出来的程序更健壮一点。而如果使用 C
> 语言的 error 宏或者函数返回值,调用者都有可能忘记检查,从而没有对错误进行
> 处理,结果造成程序莫名其面的终止或出现错误的结果。
> 
> 整型返回值没有任何语义信息。而异常却包含语义信息,有时你从类名就能够体现
> 出来。
> 
> 整型返回值缺乏相关的上下文信息。异常作为一个类,可以拥有自己的成员,这些
> 成员就可以传递足够的信息。
> 
> 异常处理可以在调用跳级。这是一个代码编写时的问题:假设在有多个函数的调用
> 栈中出现了某个错误,使用整型返回码要求你在每一级函数中都要进行处理。而使
> 用异常处理的栈展开机制,只需要在一处进行处理就可以了,不需要每级函数都处
> 理。

### 异常基本语法

```c
#include<iostream>
using namespace std;
#include"MyVector.hpp"
//1. 传统处理异常的方式,通过返回整形值标示错误
int divide01(int x,int y){
    if (y == 0){
        return -1;
    }return x / y;
}
int CallDivide01(int x,int y){
    int ret = divide01(x, y);
    if (ret == -1){
        return -100; //我这里用-100 标示除数为 0 的异常
    }
    return ret;
}
void test01(){
//处理异常
    int ret = divide01(10,0);
    if (ret == -1){
        return;
    }
    cout << "ret:" << ret << endl;
//是正确的,但是我们错误的把结果当成异常来处理了
    ret = divide01(10, -10);
    if (ret == -1){
        return;
    }
    cout << "ret:" << ret << endl;
//每一层函数都要处理异常,而且返回值不一样,有的函数用 0 标示正确,-1 标示错误,有的则相反
    等
            CallDivide01(10,20);
}
//c++异常机制基本语法
int divide02(int x, int y){
    if (y == 0){
        throw y;
    }
    return x / y;
}
int CallDivide02(int x, int y){
//divide02(x,y); //隐式再抛异常
    try{
        divide02(x,y);}
    catch (...){
//异常不处理,继续上抛异常
        cout << "CallDivide02 不处理异常,再抛异常!" << endl;
        throw;
    }
}
void test02(){
//1.发生异常之后,是跨函数
    try{
        divide02(10,0);
    }
    catch (int e){
        cout << "除数是:" << e << endl;
    }
    catch ( ...){
        cout << "抛出未知异常!" << endl;
    }
//2. 抛出异常后,可以不处理,再往上抛异常
    try{
        CallDivide02(10, 0);
    }
    catch (int e){
        cout << "除数是:" << e << endl;
    }
    catch (...){
        cout << "抛出未知异常!" << endl;
    }
}
int main(){
    test01();
    test02();
    system("pause");
    return 0;
}
```



## 栈解旋

异常被抛出后,从进入 try 块起,到异常被抛掷前,这期间在栈上构造的所有对象,都
会被自动析构。析构的顺序与构造的顺序相反,这一过程称为栈的解旋(unwinding).

```c
//
// Created by bruce on 18-5-30.
//

#include<iostream>
using namespace std;
#include"MyVector.hpp"
//异常类
class MyException{
public:
    MyException(){
        cout << "构造函数!" << endl;
    }
    ~MyException(){
        cout << "析构函数!" << endl;
    }
};
int divide(){
    MyException ex1, ex2;
    cout << "要发生异常了...." << endl;
    throw 1;
}
int main(){
    try{
        divide();
    }
    catch(int e){
        cout << "捕获异常!" << endl;
    }
    system("pause");
    return 0;
}
```

## 异常接口声明

> - 为了加强程序的可读性,可以在函数声明中列出可能抛出异常的所有类型,例如:void func() throw(A,B,C);这个函数 func 能够且只能抛出类型 A,B,C 及其子类型的异常。
> - 如果在函数声明中没有包含异常接口声明,则此函数可以抛任何类型的异常,例如:void func()
> - 一个不抛任何类型异常的函数可声明为:void func() throw()
> -  如果一个函数抛出了它的异常接口声明锁不允许抛出的异常,unexcepted 函数会被调用,该函数默认行为调用 terminate 函数中断程序。

```c
#include<iostream>
using namespace std;
#include"MyVector.hpp"
//表明这个函数能够且只能抛出这三种类型的异常
void TestException01() throw(int, float, char){
//如果在类的内部,你抛出非指定三种异常类型,那么会导致程序调用 terminate 函数,中断执行
    throw "exception";
}
//如果你这个函数禁止抛任何异常
void TestException02() throw(){
    throw "exception"; //如果强制抛异常,那么也会导致程序调用 terminate 函数,中断执行
}
//这种普通函数,在函数名后不加 throw,那么可以抛出任何类型异常
void TestException03(){
    throw "exception";
}
int main(){
//TestException01();//TestException02();
    try{
        TestException03();
    }
    catch (char* e){
        cout << "异常捕获:" << e << endl;
    }
    system("pause");
    return 0;
}
```



## 异常类型和异常变量的生命周期

```c
#include<iostream>
using namespace std;
#include"MyVector.hpp"
//普通处理异常方式 通过 return err
int copy01(char* to,char* from){
    if (to == NULL){
        return -1;
    }
    if (from == NULL){
        return -2;
    }
    while (*from != '\0'){
        *to = *from;
        to++;
        from++;
    }
    return 0;
}
//普通处理异常void test01(){
char* src = "abcdefg";
char buf[1024] = { 0 };
int ret = copy01(buf,src);
if (ret < 0){
switch (ret)
{
case -1:
cout << "目标空间为空!" << endl;
break;
case -2:
cout << "源空间为空!" << endl;
break;
default:
cout << "其他异常问题!" << endl;
break;
}
return;
}
cout << "buf:" << buf << endl;
}
//抛出 int 类型异常
void copy02(char* to, char* from){
    if (to == NULL){
        throw
                -1;
    }
    if (from == NULL){
        throw - 2;
    }
    while (*from != '\0'){
        *to = *from;
        to++;
        from++;
    }
}
void test02(){
    char* src = "abcdefg";
    char buf[1024] = { 0 };
    try{
        copy02(buf, NULL);}
    catch (int e){
        switch (e){
            case -1:
                cout << "目标空间为空!" << endl;
                break;
            case -2:
                cout << "源空间为空!" << endl;
                break;
            default:
                cout << "其他异常问题!" << endl;
                break;
        }
    }
    cout << "buf:" << buf << endl;
}
//抛出 char*类型异常
void copy03(char* to, char* from){
    if (to == NULL){
        throw "目标空间为空!";
    }
    if (from == NULL){
        throw "源空间为空!";
    }
    while (*from != '\0'){
        *to = *from;
        to++;
        from++;
    }
}
void test03(){
    char* src = "abcdefg";
    char buf[1024] = { 0 };
    try{
        copy03(buf, NULL);
    }
    catch (char* e){
        cout << e << endl;;
    }
    cout << "buf:" << buf << endl;}
//抛出对象类型异常
//定义异常类
//目标空间空异常类
class TargetSpaceNullException{
public:
    TargetSpaceNullException(){
        cout << "TargetSpaceNullException 构造函数!" << endl;
    }
    TargetSpaceNullException(const TargetSpaceNullException& ex){
        cout << "TargetSpaceNullException 拷贝构造!" << endl;
    }
    ~TargetSpaceNullException(){
        cout << "TargetSpaceNullException 析构函数!" << endl;
    }
};
//源空间空异常类
class SourceSpaceNullException{
public:
    SourceSpaceNullException(){
        cout << "SourceSpaceNullException 构造函数!" << endl;
    }
    SourceSpaceNullException(const SourceSpaceNullException& ex){
        cout << "SourceSpaceNullException 拷贝构造!" << endl;
    }
    ~SourceSpaceNullException(){
        cout << "SourceSpaceNullException 析构函数!" << endl;
    }
};
void copy04(char* to, char* from){
    if (to == NULL){
        throw TargetSpaceNullException(); //产生匿名对象
    }
    if (from == NULL){
//throw &(SourceSpaceNullException());
        throw new SourceSpaceNullException();
    }
    while (*from != '\0'){
        *to = *from;
        to++;
        from++;}
}
void test04(){
    char* src = "abcdefg";
    char buf[1024] = { 0 };
    try{
        copy04(buf, NULL);
    }
    catch (TargetSpaceNullException& e){ //是将匿名对象进行拷贝了吗?
//结论 1:如果接受异常时,用异常变量去接,那么会拷贝匿名异常对象
//结论 2:如果接受异常时,用引用去接,那么不需要拷贝
        cout << "目标空间为空!" << endl;
    }
    catch (SourceSpaceNullException* e){
//结论 3 如果接受指针,那么要考虑指针是否是野指针的问题
//这里应该手动管理异常类的生命周期
        cout << "源空间为空!" << endl;
        delete e; //析构异常对象空间
    }
    cout << "buf:" << buf << endl;
}
//继承在异常中的使用
//抽象异常基类
class AbstractBaseException{
public:
    virtual void printExceptionError() = 0;
};
//目标空间空异常类
class MyTargetSpaceNullException : public AbstractBaseException{
public:
    MyTargetSpaceNullException(){
        cout << "MyTargetSpaceNullException 构造函数!" << endl;
    }
    MyTargetSpaceNullException(const MyTargetSpaceNullException& ex){
        cout << "TargetSpaceNullException 拷贝构造!" << endl;
    }
    ~MyTargetSpaceNullException(){
        cout << "MyTargetSpaceNullException 析构函数!" << endl;
    }
    virtual void printExceptionError(){
        cout << "目标空间为空!" << endl;
    }};
//源空间空异常类
class MySourceSpaceNullException : public AbstractBaseException{
public:
    MySourceSpaceNullException(){
        cout << "MySourceSpaceNullException 构造函数!" << endl;
    }
    MySourceSpaceNullException(const MySourceSpaceNullException& ex){
        cout << "MySourceSpaceNullException 拷贝构造!" << endl;
    }
    ~MySourceSpaceNullException(){
        cout << "MySourceSpaceNullException 析构函数!" << endl;
    }
    virtual void printExceptionError(){
        cout << "源空间为空!" << endl;
    }
};
void copy05(char* to, char* from){
    if (to == NULL){
        throw MyTargetSpaceNullException();
    }
    if (from == NULL){
        throw MySourceSpaceNullException();
    }
    while (*from != '\0'){
        *to = *from;
        to++;
        from++;
    }
}
void test05(){
    char* src = "abcdefg";
    char buf[1024] = { 0 };
    try{
        copy05(NULL, src);
    }
    catch (AbstractBaseException& e){
        e.printExceptionError();
    }
    cout << "buf:" << buf << endl;
}int main(){
//test01();
//test02();
//test03();
//test04();
    test05();
    system("pause");
    return 0;
}
```

## c++标准库异常

![image.png](https://upload-images.jianshu.io/upload_images/6836439-28abe217ddedae69.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**标准异常类的成员**

>1. 在上述继承体系中,每个类都有提供了构造函数、复制构造函数、和赋值操作符重载。
>2. logic_error 类及其子类、runtime_error 类及其子类,它们的构造函数是接受一个 string类型的形式参数,用于异常信息的描述
>
>
>3. 所有的异常类都有一个 what()方法,返回 const char* 类型(C 风格字符串)的值,描述异常信息。

**标准异常类的具体描述**

![image.png](https://upload-images.jianshu.io/upload_images/6836439-45405e39d936772b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![image.png](https://upload-images.jianshu.io/upload_images/6836439-d03f3c085c53b7d5.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![image.png](https://upload-images.jianshu.io/upload_images/6836439-5fb182b45729ac73.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**编写自己的异常类**

1. 为什么要编写自己的异常类?
  1 标准库中的异常是有限的;
  2 在自己的异常类中,可以添加自己的信息。
  (标准库中的异常类值允许设置一个用来描述
  异常的字符串)。
2. 如何编写自己的异常类?
  1 建议自己的异常类要继承标准异常类。因为 C++中可以抛出任何类型的异常,所以我们
  的异常类可以不继承自标准异常,但是这样可能会导致程序混乱,尤其是当我们多人协同开
  发时。
  2 当继承标准异常类时,应该重载父类的 what 函数和虚析构函数。
  3 因为栈展开的过程中,要复制异常类型,那么要根据你在类中添加的成员考虑是否提供
  自己的复制构造函数。

```c
#define _CRT_SECURE_NO_WARNINGS
#include<iostream>
using namespace std;
#include"MyVector.hpp"
//标准库异常class Person{
public:
Person(int age,string name){
    if (age < 0 || age > 100){
        throw out_of_range("年龄应该在 0-100 之间的数字!");
    }
    mName = name;
    mAge = age;
}
public:
string mName;
int mAge;
};
void test01(){
    try{
        Person p(101, "aaa");
    }
    catch (out_of_range& e){
        cout << e.what() << endl;
    }
}
//自定义异常类
class MyOutRangeException : public exception{
public:
    MyOutRangeException(const char* error){
        int len = strlen(error) + 1;
        this->pError = new char[len];
        strcpy(this->pError,error);
    }
    virtual const char*
    what() const{
        return this->pError;
    }
    virtual ~MyOutRangeException(){
        cout << "析构函数!" << endl;
        if (pError != NULL){
            delete[] this->pError;
        }
    }
public:
    char* pError;
};class Person02{
public:
    Person02(int age, string name){
        if (age < 0 || age > 100){
            throw MyOutRangeException("年龄应该在 0-100 之间的数字!");
        }
        mName = name;
        mAge = age;
    }
public:
    string mName;
    int mAge;
};
void test02(){
    try{
        Person02 p(101,"aaa");
    }
    catch (exception& e){
        cout << e.what() << endl;
    }
}
int main(){
    test01();
    test02();
    system("pause");
    return 0;
}
```

